spring:
  datasource:
    url: jdbc:mysql://localhost:3306/customer?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: nextlevel
    password: nextlevel
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect