app:
  auth:
    resetPasswordLink: http://localhost:3000/reset-password
    tokenSecret: 413F4428472B4B6250655368566D5970337336763979244226452948404D6351
    tokenExpirationMsec: 86400000
    cookieMaxAge: 86400000
    cookiePath: /
    secretKey: user secret key
    customerServiceUrl: http://localhost:8081
spring:
  application-name: AdminService
  config:
    import: hari.yml
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

