app:
  auth:
    customerServiceUrl: http://localhost:8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/loans?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: nextlevel
    password: nextlevel
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        session_factory:
          interceptor: com.cg.config.AuditLoggingInterceptor